add self test step

diff --git a/.github/workflows/build_robotframework_aio.yml b/.github/workflows/build_robotframework_aio.yml
--- a/.github/workflows/build_robotframework_aio.yml
+++ b/.github/workflows/build_robotframework_aio.yml
@@ -609,7 +609,7 @@ jobs:
       fail-fast: false
       matrix:
         version: [original, extended]
-        distro: [osd7]
+        distro: [osd7, osd8, oss]
     env:
       BUNDLE_NAME: "--bundle_name 'RobotFramework AIO'"
       AIO_NAME: "RobotFramework AIO (${{ matrix.version }})"
@@ -641,7 +641,6 @@ jobs:
         uses: docker/build-push-action@v5
         with:
           context: .
-          # Point to the specific Dockerfile for each distro
           file: ./docker/${{ matrix.distro }}/Dockerfile
           push: true
           load: true
@@ -672,66 +671,100 @@ jobs:
           name: docker-image-${{ matrix.distro }}-${{ matrix.version }}
           path: ${{ env.AIO_VERSION }}-${{ matrix.distro }}-${{ matrix.version }}.tar
 
-  # install-test-docker:
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       version: [original, extended]
-  #       distro: osd7
-  #   name: Test AIO Docker Container (${{ matrix.distro }}-${{ matrix.version }})
-  #   runs-on: ubuntu-latest
-  #   needs: build-docker
-  #   if: ${{ ! failure() && ! cancelled() }}
+  install-test-docker:
+    strategy:
+      fail-fast: false
+      matrix:
+        version: [original, extended]
+        distro: [osd7, osd8, oss]
+    name: Test AIO Docker Container (${{ matrix.distro }}-${{ matrix.version }})
+    runs-on: ubuntu-latest
+    needs: [ build-docker, trigger-aio ]
+    if: ${{ ! failure() && ! cancelled() }}
 
-  #   container:
-  #     image: ghcr.io/${{ github.repository_owner }}/robotframework-aio:${{ needs.build-docker.outputs.aio_version }}-${{ matrix.distro }}-${{ matrix.version }}
-  #     options: --user root
-  #     credentials:
-  #       username: ${{ github.actor }}
-  #       password: ${{ secrets.GITHUB_TOKEN }}
+    # container:
+    #   image: ghcr.io/${{ github.repository_owner }}/robotframework-aio:${{ needs.build-docker.outputs.aio_version }}-${{ matrix.distro }}-${{ matrix.version }}
+    #   options: --user root
+    #   credentials:
+    #     username: ${{ github.actor }}
+    #     password: ${{ secrets.GITHUB_TOKEN }}
 
-  #   env:
-  #     REPO_CONFIG: "./config/repositories/repositories_${{ matrix.version }}.conf"
-  #     TEST_CONFIG: "./config/testtrigger_config_${{ matrix.version }}.json"
-  #     RobotDevtools: "/opt/rfwaio/devtools"
+    env:
+      REPO_CONFIG: "./config/repositories/repositories_${{ matrix.version }}.conf"
+      TEST_CONFIG: "./config/testtrigger_config_${{ matrix.version }}.json"
+      RobotDevtools: "/opt/rfwaio/devtools"
+      AIO_IMAGE: "ghcr.io/${{ github.repository_owner }}/robotframework-aio:${{ needs.build-docker.outputs.aio_version }}-${{ matrix.distro }}-${{ matrix.version }}"
 
-  #   steps:
-  #     - name: Checkout source
-  #       uses: actions/checkout@v4
+    steps:
+      - name: Checkout source
+        uses: actions/checkout@v4
 
-  #     - name: Clone repositories
-  #       run: |
-  #         export REPOSITORY="${{needs.trigger-aio.outputs.repository}}"
-  #         export PULL_REQUEST_BRANCH="${{needs.trigger-aio.outputs.branch}}"
-  #         chmod +x ./cloneall
-  #         ./cloneall --config-file=${REPO_CONFIG}
+      - name: Clone repositories
+        run: |
+          export REPOSITORY="${{needs.trigger-aio.outputs.repository}}"
+          export PULL_REQUEST_BRANCH="${{needs.trigger-aio.outputs.branch}}"
+          chmod +x ./cloneall
+          ./cloneall --config-file=${REPO_CONFIG}
 
-  #     - name: Run static code analysis
-  #       run: |
-  #         # Initialize environment variables inside the container
-  #         . /opt/rfwaio/linux/set_robotenv.sh
-  #         python3 test/aio-static-code-trigger/aio_static_code_trigger.py 2>&1 | tee console_log.txt
+      - name: Start RabbitMQ container
+        run: |
+          cur_dir=$(pwd)
+          cd ../python-rabbitmq-messagebus/test/docker
+          docker compose up -d
+          cd "$cur_dir"
 
-  #     - name: Run tests inside Container
-  #       run: |
-  #         . /opt/rfwaio/linux/set_robotenv.sh
-  #         # Run the main test trigger script
-  #         python3 test/aio-test-trigger/aio-test-trigger.py --configfile ${TEST_CONFIG} 2>&1 | tee console_log.txt
+          for i in {1..30}; do
+            nc -z localhost 5672 && echo "RabbitMQ is up" && break
+            echo "Waiting for RabbitMQ to start..."
+            sleep 2
+          done
 
-  #     - name: Run tests coverage
-  #       run: |
-  #         . /opt/rfwaio/linux/set_robotenv.sh
-  #         python3 test/aio-test-trigger/aio-test-coverage.py --configfile ${TEST_CONFIG} 2>&1 | tee console_log.txt
+      - name: Run tests inside AIO Container
+        run: |
+          WORKSPACE_PARENT=$(dirname ${{ github.workspace }})
+          CURRENT_REPO=$(basename ${{ github.workspace }})
 
-  #     - name: Upload test result
-  #       if: success() || failure()
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: docker-test-logs-${{ matrix.distro }}-${{ matrix.version }}
-  #         path: |
-  #           ${{ runner.workspace }}/**/*/aiotestlogfiles/*
-  #           ${{ runner.workspace }}/**/*/testlogfiles/*
-  #           ${{ runner.workspace }}/**/*/console_log.txt
+          docker run --rm \
+            --network host \
+            -v $WORKSPACE_PARENT:/workspace \
+            -w /workspace/$CURRENT_REPO \
+            ${AIO_IMAGE} \
+            bash -c "
+              # Create a symbolic link to map the host tutorial folder to the expected hardcoded container path
+              mkdir -p /root/RobotTest/tutorial
+              cp -r /opt/rfwaio/tutorial/* /root/RobotTest/tutorial/
+              # Map the standalone JAR to the legacy extension path to satisfy tool dependencies
+              mkdir -p /usr/local/lib/plantuml
+              sudo curl -L https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar -o /usr/local/lib/plantuml/plantuml.jar
+              mkdir -p /opt/rfwaio/robotvscode/data/extensions/jebbs.plantuml-2.18.1/
+              sudo ln -s /usr/local/lib/plantuml/plantuml.jar /opt/rfwaio/robotvscode/data/extensions/jebbs.plantuml-2.18.1/plantuml.jar
+              # Run static code analysis
+              . /opt/rfwaio/linux/set_robotenv.sh
+              python3 test/aio-static-code-trigger/aio_static_code_trigger.py 2>&1 | tee static_code_log.txt
+
+              # Run tests coverage
+              python3 test/aio-test-trigger/aio-test-coverage.py --configfile ${TEST_CONFIG} 2>&1 | tee coverage_console_log.txt
+
+              # Run tests
+              python3 test/aio-test-trigger/aio-test-trigger.py --configfile ${TEST_CONFIG} 2>&1 | tee test_log.txt
+              # Get system error code from python program (Catching the test exit code)
+              exit_code=\${PIPESTATUS[0]}
+              if [ \$exit_code -ne 0 ]; then
+                  exit 1
+              fi
+            "
+
+      - name: Upload test result
+        if: success() || failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: docker-test-logs-${{ matrix.distro }}-${{ matrix.version }}
+          path: |
+            ${{ runner.workspace }}/**/*/aiotestlogfiles/*
+            ${{ runner.workspace }}/**/*/testlogfiles/*
+            ${{ github.workspace }}/static_code_log.txt
+            ${{ github.workspace }}/coverage_console_log.txt
+            ${{ github.workspace }}/test_log.txt
 
   entire-artifacts:
     name: Entire Artifacts
